const workshops = [
  // ==================== YOGA SECTION ====================
  {
    slug: "21day",
    section: "yoga",
    sectionLabel: "Yoga",
    sectionLabelKn: "ಯೋಗ",
    title: "21-Day Holistic Challenge",
    titleKn: "21 ದಿನಗಳ ಸಂಪೂರ್ಣ ಆರೋಗ್ಯ ಸವಾಲು",
    category: "holistic",
    categoryLabel: "Holistic Health",
    description: "Our flagship habit reset program. Taught in Kannada, covering morning rising, daily yoga, diet recipes, early dinner, and water therapy.",
    descriptionKn: "ನಮ್ಮ ಪ್ರಮುಖ ಅಭ್ಯಾಸ ಮರುಹೊಂದಿಸುವ ಕಾರ್ಯಕ್ರಮ. ಮುಂಜಾನೆ ಏಳುವುದು, ದೈನಂದಿನ ಯೋಗ, ಆಹಾರ ಪಾಕವಿಧಾನಗಳು, ಆರಂಭಿಕ ಊಟ ಮತ್ತು ಜಲ ಚಿಕಿತ್ಸೆ.",
    price: 499,
    originalPrice: 999,
    duration: "4 Batches Daily",
    timingSlot: "5:30 AM or 6:30 AM IST",
    timingIcon: "alarm",
    badge: "Flagship",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAeW6X-Xbnzzibn5vBblDaMOKZ9I5pN1IM06R4zDRuOdkD-9Wo6S3m7m_J0dK0qdWJGyueyVkmQmwzk5BxGQIVpWVDXZhXVm80sJovk1mFz71N5ZhVHUenH4R4_9Bk3eTDTvbBT952IM8xLqwXcNFPzE8Fzq9jksT6GmEJpllQ1Vja4PrcRzI8jJaqJDwQsP41wdO6-Hd03gbX80NkyitBR2PCUNesuc1Hu0ObZ1sat3JWb4IooqiCC",
    features: [
      "Morning rising routine",
      "Sattvic Mysore diet guide",
      "24-Hr Zoom recordings",
      "Private WhatsApp support"
    ],
    spotsLeft: 5,
    isActive: true
  },
  {
    slug: "ashtanga-yoga",
    section: "yoga",
    sectionLabel: "Yoga",
    sectionLabelKn: "ಯೋಗ",
    title: "Traditional Ashtanga Yoga",
    titleKn: "ಸಾಂಪ್ರದಾಯಿಕ ಮೈಸೂರು ಶೈಲಿಯ ಯೋಗ",
    category: "vinyasa",
    categoryLabel: "Traditional Vinyasa",
    description: "Traditional Mysore-style dynamic Vinyasa flow, Ujjayi breathing, and focus point (Tristhana) integration. Systematically taught.",
    descriptionKn: "ಸಾಂಪ್ರದಾಯಿಕ ಮೈಸೂರು ಶೈಲಿಯ ಡೈನಾಮಿಕ್ ವಿನ್ಯಾಸ, ಉಜ್ಜಾಯೀ ಪ್ರಾಣಾಯಾಮ ಮತ್ತು ತ್ರಿಸ್ಥಾನ ತತ್ವಗಳೊಂದಿಗೆ ಕ್ರಮಬದ್ಧ ಬೋಧನೆ.",
    price: 419,
    originalPrice: 899,
    duration: "60 Mins Daily",
    timingSlot: "5:30 – 6:30 AM IST",
    timingIcon: "spa",
    badge: "Mysuru Heritage",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCwnGj6pKZVyj-nq1nUw4LlIBES-tMfCjP7DKKyaqFYd72ASHCZGIy5zhDwwKdBx1QpV_9-cd4RD3xSBEgEU8zTZhkGboliDpvUZZBdmS2QvMJU3wyDdLBKH-81-sVLg56VbNuaYfGBaoKcbhPy5X1nDmwfPE2K69BaDyz1PZ_oE-0jlA8G1EqDdz5m82UOqe8lrKbnxZ7SEoWi-xBgiHLigTWHtcdhQxL_KmcpOdaOerCMfY8j4JZ_",
    features: [
      "Mysore Primary Series foundations",
      "Tristhana focus methodology",
      "Ujjayi pranayama breathwork",
      "Safe physical alignment"
    ],
    spotsLeft: 3,
    isActive: true
  },
  {
    slug: "ladies-yoga",
    section: "yoga",
    sectionLabel: "Yoga",
    sectionLabelKn: "ಯೋಗ",
    title: "Ladies Yoga Batch",
    titleKn: "ಮಹಿಳೆಯರ ವಿಶೇಷ ಯೋಗ ಅಭ್ಯಾಸ",
    category: "women",
    categoryLabel: "Women’s Health",
    description: "Women-only batch focusing on pelvic floor strength, core conditioning, thyroid health, and hormonal balance.",
    descriptionKn: "ಪೆಲ್ವಿಕ್ ಫ್ಲೋರ್ ಬಲ, ಕೋರ್ ಕಂಡೀಷನಿಂಗ್, ಥೈರಾಯ್ಡ್ ಆರೋಗ್ಯ ಮತ್ತು ಹಾರ್ಮೋನ್ ಸಮತೋಲನದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುವ ಮಹಿಳೆಯರಿಗೆ ಮಾತ್ರ ಮೀಸಲಾದ ಬ್ಯಾಚ್.",
    price: 179,
    originalPrice: 399,
    duration: "60 Mins Daily",
    timingSlot: "11:30 AM – 12:30 PM IST",
    timingIcon: "sunny",
    badge: "Women-Only",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEOt2PxOnG_oLgwz0XPk14P5RknxKLUrYQllO9WXA6YojXJ28wzsk5wquzc5VLuSvph2mnDFLBkoPVcK6H91NdTx09v-jHqTwbp2827W3CRCiqGpBvJC4oxhoauU9cUb4Ge4q8j-wr6JodXzCP3mvmguwxhQMewz7VqUqblbg1oh2VSNUik8Nt4qCforORq3FRV33a47BhPN--31GttinC2ZsczJoHuaqxSCWmv0ThpBlUoU6KLCvU",
    features: [
      "Hormonal balancing asanas",
      "PCOD / PCOS gentle modifications",
      "Pelvic floor rehabilitation",
      "Supportive women cohort"
    ],
    spotsLeft: 4,
    isActive: true
  },
  {
    slug: "strength-training",
    section: "yoga",
    sectionLabel: "Yoga",
    sectionLabelKn: "ಯೋಗ",
    title: "Strength Training & Calisthenics",
    titleKn: "ದೇಹದ ಶಕ್ತಿ ಮತ್ತು ದೃಢತೆ ತರಬೇತಿ",
    category: "strength",
    categoryLabel: "Core & Muscle",
    description: "Daily bodyweight training, conditioning planks, and high-intensity stamina finishers. 100% equipment-free workouts.",
    descriptionKn: "ದೈನಂದಿನ ಶಾರೀರಿಕ ತೂಕದ ವ್ಯಾಯಾಮ, ಪ್ಲಾಂಕ್‌ಗಳು ಮತ್ತು ಸ್ಟ್ಯಾಮಿನಾ ಹೆಚ್ಚಿಸುವ ತರಬೇತಿ. ಶೇಕಡಾ 100 ರಷ್ಟು ಸಲಕರಣೆ ರಹಿತ ಅಭ್ಯಾಸ.",
    price: 419,
    originalPrice: 799,
    duration: "60 Mins Daily",
    timingSlot: "6:30 – 7:30 AM IST",
    timingIcon: "fitness_center",
    badge: "Conditioning",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBaovdrEA20fBsc8MNpN-IdZDWOFWmudRa9ddQIjXQ7wMhhLMS1Yefql3G2_DFQylnazjCgFhrkLPNdVSp0D2lHEYomxs-_83swuj_ICLr05ERYZOqB8l2MR8Za_wEkptlPYSM5P168n3dzLA-QG-1HhCqmfP6xb_J6Mr3ogsTUGGUsTqHnclCjc5fu93WQCNAwEi2wwORK4JwObRB92bMPAXi04hpKBgywcVc3iQ4K_t497e2NdEfh",
    features: [
      "Bodyweight calisthenics",
      "Core compression strength",
      "Spine resilience drills",
      "Metabolism boosting finishers"
    ],
    spotsLeft: 7,
    isActive: true
  },
  {
    slug: "kids-yoga",
    section: "yoga",
    sectionLabel: "Yoga",
    sectionLabelKn: "ಯೋಗ",
    title: "Kids Yoga Class",
    titleKn: "ಮಕ್ಕಳ ಏಕಾಗ್ರತೆ ಮತ್ತು ನೆನಪಿನ ಶಕ್ತಿ",
    category: "kids",
    categoryLabel: "Ages 6 – 14",
    description: "Gamified movement storytelling and posture challenges to build focus, cognitive attention, and healthy early rising routines before school.",
    descriptionKn: "ಏಕಾಗ್ರತೆ, ಜ್ಞಾಪಕ ಶಕ್ತಿ ಮತ್ತು ಶಾಲೆಯ ಮುನ್ನ ಆರೋಗ್ಯಕರ ಮುಂಜಾನೆ ದಿನಚರಿಯನ್ನು ರೂಪಿಸಲು ಕಥೆಗಳ ಮೂಲಕ ಕಲಿಸುವ ಯೋಗ.",
    price: 239,
    originalPrice: 499,
    duration: "60 Mins Daily",
    timingSlot: "5:30 – 6:30 AM IST",
    timingIcon: "child_care",
    badge: "Kids 6-14",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAWx2WuINFmClRF4E05mMQnZ18XYMu2qyyyVug6WRymBZxnnLaCi-Q-PQyA5YioQydeiOQC4EUJc72ZBDanMUddS_23DBNt846OpI8NwtJFOaLS1QhUnSj_nRj-ySad5LvxScOmD1RBvr4mHaQPdnMEtXHQFMh7RwAmk4GbB1kYK_A3QTnI_dam6pMiapE_z0ikK8UlPb2pfC6SE4dBufHXlsAoAThTQ3YSbuOA_AF9dj17DRhSEQe7",
    features: [
      "Posture alignment for young bones",
      "Focus & memory exercises",
      "Playful animal asanas",
      "Early morning discipline"
    ],
    spotsLeft: 9,
    isActive: true
  },
  {
    slug: "pranayama-breathwork",
    section: "yoga",
    sectionLabel: "Yoga",
    sectionLabelKn: "ಯೋಗ",
    title: "Pranayama & Breathwork Shala",
    titleKn: "ಪ್ರಾಣಾಯಾಮ ಮತ್ತು ಉಸಿರಾಟದ ಶಕ್ತಿ",
    category: "pranayama",
    categoryLabel: "Prana & Breath",
    description: "Deep yogic breathing practices, lung capacity expansion, anxiety release, and morning nervous system regulation.",
    descriptionKn: "ಆಳವಾದ ಯೋಗಿಕ ಉಸಿರಾಟ, ಶ್ವಾಸಕೋಶದ ಸಾಮರ್ಥ್ಯ ವೃದ್ಧಿ, ಆತಂಕ ನಿವಾರಣೆ ಮತ್ತು ಮುಂಜಾನೆಯ ನರಮಂಡಲದ ಶಾಂತತೆಗಾಗಿ ವಿಶೇಷ ತರಗತಿ.",
    price: 299,
    originalPrice: 599,
    duration: "45 Mins Daily",
    timingSlot: "6:00 – 6:45 AM IST",
    timingIcon: "air",
    badge: "Daily Prana",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    features: [
      "Nadi Shodhana & Kapalabhati mastery",
      "Lung capacity enhancement",
      "Vagus nerve stimulation",
      "Morning mindful silence"
    ],
    spotsLeft: 8,
    isActive: true
  },

  // ==================== MUSIC & SOUND SECTION ====================
  {
    slug: "sushii-nights",
    section: "music",
    sectionLabel: "Music & Sound",
    sectionLabelKn: "ಸಂಗೀತ ಮತ್ತು ನಾದ",
    title: "Sushii Nights Sleep Flow",
    titleKn: "ನೆಮ್ಮದಿಯ ನಿದ್ದೆಗಾಗಿ ರಾತ್ರಿ ನಿಯಮ",
    category: "sleep",
    categoryLabel: "Sleep & Wind Down",
    description: "30-minute bedtime relaxation, breathing exercises, and guided sleep meditation to release desk stiffness and insomnia.",
    descriptionKn: "ಕಂಪ್ಯೂಟರ್ ಕೆಲಸದ ದಣಿವು ಮತ್ತು ನಿದ್ರಾಹೀನತೆಯನ್ನು ಹೋಗಲಾಡಿಸಲು 30 ನಿಮಿಷಗಳ ಮಲಗುವ ಮುನ್ನ ವಿಶ್ರಾಂತಿ, ಪ್ರಾಣಾಯಾಮ ಮತ್ತು ಧ್ಯಾನ.",
    price: 49,
    originalPrice: 149,
    duration: "30 Mins Daily",
    timingSlot: "9:30 – 10:00 PM IST",
    timingIcon: "bedtime",
    badge: "Bedtime Sound",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDbaKT0sNCQtBXCG914Q1xqI0ZEX1A9U4K4nvafTXroWHLO5wFb7XjYz5UZyvyIDiZsmupXuCISTZqp3TrS3a4jPXwGVETNqkjQFWu8qcvGJONOCoqwAuA5yKatfyEeo_yf-A5DlsYwCHl1Ctry7uXEuI__lku9QLSkPuhAVHN3MrmAKU1nm7v_UJspEUd24msZ9TyGIA-XReVaVeQJy7J7CIP6PZFhI1frD8pUdecxjhbAg0grQ3T3",
    features: [
      "Bedtime hip openers",
      "Nadi Shodhana Pranayama",
      "Guided Yoga Nidra",
      "Insomnia recovery soundscapes"
    ],
    spotsLeft: 12,
    isActive: true
  },
  {
    slug: "nada-flute-bath",
    section: "music",
    sectionLabel: "Music & Sound",
    sectionLabelKn: "ಸಂಗೀತ ಮತ್ತು ನಾದ",
    title: "Nada Yoga & Bamboo Flute Sound Bath",
    titleKn: "ನಾದ ಯೋಗ ಮತ್ತು ಬಿದಿರಿನ ಕೊಳಲು ಧ್ಯಾನ",
    category: "sound",
    categoryLabel: "Sound Healing",
    description: "Immersive acoustic sound bath with authentic Indian bamboo flute ragas, Tibetan singing bowls, and nervous system restorative acoustics.",
    descriptionKn: "ಶಾಂತಿಯುತ ಬಿದಿರಿನ ಕೊಳಲಿನ ರಾಗಗಳು, ಟಿಬೆಟಿಯನ್ ಬೌಲ್ ನಾದ ಮತ್ತು ಆಳವಾದ ವಿಶ್ರಾಂತಿಯನ್ನು ನೀಡುವ ಲೈವ್ ನಾದೋಪಾಸನೆ ತರಗತಿ.",
    price: 349,
    originalPrice: 699,
    duration: "60 Mins",
    timingSlot: "8:00 – 9:00 PM IST (Wed & Sat)",
    timingIcon: "music_note",
    badge: "Acoustic Bath",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    features: [
      "Live Mysuru bamboo flute ragas",
      "Vagus nerve acoustic restoration",
      "Tibetan singing bowl harmonics",
      "Stress & emotional detox"
    ],
    spotsLeft: 6,
    isActive: true
  },
  {
    slug: "vedic-chanting",
    section: "music",
    sectionLabel: "Music & Sound",
    sectionLabelKn: "ಸಂಗೀತ ಮತ್ತು ನಾದ",
    title: "Vedic Chanting & Om Resonance",
    titleKn: "ವೇದ ಮಂತ್ರ ಪಠಣ & ಓಂಕಾರ ನಾದ",
    category: "chanting",
    categoryLabel: "Sacred Harmonics",
    description: "Vocal frequency harmonics, traditional Shanti mantra chanting in Kannada script, and deep chakra resonant vibrations.",
    descriptionKn: "ಸರಳ ಸಂಸ್ಕೃತ ಮತ್ತು ಕನ್ನಡ ಲಿಪಿಯೊಂದಿಗೆ ವೇದ ಮಂತ್ರಗಳ ಪಠಣ, ಧ್ವನಿ ತರಂಗಗಳ ತರಬೇತಿ ಮತ್ತು ಮನಸ್ಸಿನ ಏಕಾಗ್ರತೆಗಾಗಿ ಓಂಕಾರ ಧ್ಯಾನ.",
    price: 249,
    originalPrice: 499,
    duration: "45 Mins",
    timingSlot: "7:00 – 7:45 PM IST",
    timingIcon: "graphic_eq",
    badge: "Vocal Resonance",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80",
    features: [
      "Accurate Vedic pronunciation",
      "Chakra frequency humming",
      "Shanti mantras for inner calm",
      "Bilingual chant lyrics PDF"
    ],
    spotsLeft: 10,
    isActive: true
  },

  // ==================== OTHER ACTIVITIES SECTION ====================
  {
    slug: "sattvic-cooking",
    section: "other",
    sectionLabel: "Other Activities",
    sectionLabelKn: "ಇತರ ಚಟುವಟಿಕೆಗಳು",
    title: "Mysore Sattvic Cooking Workshop",
    titleKn: "ಮೈಸೂರು ಸಾತ್ವಿಕ ಪಾಕಶಾಸ್ತ್ರ ತರಬೇತಿ",
    category: "cooking",
    categoryLabel: "Ayurvedic Food",
    description: "Farm-to-table Ayurvedic culinary masterclass. Learn Karnataka millet recipes, digestion-healing spice alchemies, and gut health drinks.",
    descriptionKn: "ದೇಹಕ್ಕೆ ಲಘು ಮತ್ತು ಮನಸ್ಸಿಗೆ ಶಾಂತಿ ನೀಡುವ ಶುದ್ಧ ಸಾತ್ವಿಕ ಅಡುಗೆಗಳು, ಸಿರಿಧಾನ್ಯಗಳ ಬಳಕೆ ಮತ್ತು ಆಯುರ್ವೇದ ಮಸಾಲೆಗಳ ರಹಸ್ಯವನ್ನು ಕಲಿಯಿರಿ.",
    price: 399,
    originalPrice: 799,
    duration: "90 Mins Masterclass",
    timingSlot: "4:30 – 6:00 PM IST (Saturdays)",
    timingIcon: "restaurant",
    badge: "Nutrition Lab",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    features: [
      "Ancient Karnataka millet dishes",
      "Digestive spices & herbal teas",
      "Sugar-free seasonal sweets",
      "Printable Sattvic recipe ebook"
    ],
    spotsLeft: 8,
    isActive: true
  },
  {
    slug: "chamundi-walk",
    section: "other",
    sectionLabel: "Other Activities",
    sectionLabelKn: "ಇತರ ಚಟುವಟಿಕೆಗಳು",
    title: "Chamundi Sunrise Nature Walk & Forest Silence",
    titleKn: "ಚಾಮುಂಡಿ ಬೆಟ್ಟದ ಮುಂಜಾನೆ ನಡಿಗೆ & ಪ್ರಕೃತಿ ಧ್ಯಾನ",
    category: "retreat",
    categoryLabel: "Mindful Nature",
    description: "Mindful silence walking up the historic Chamundi steps, sunrise meditation overlooking Mysuru palace city, and forest prana intake.",
    descriptionKn: "ಚಾಮುಂಡಿ ಬೆಟ್ಟದ ಸಾಂಪ್ರದಾಯಿಕ ಮೆಟ್ಟಿಲುಗಳಲ್ಲಿ ಮೌನ ನಡಿಗೆ, ಮುಂಜಾನೆಯ ತಂಪಾದ ಗಾಳಿಯಲ್ಲಿ ಧ್ಯಾನ ಮತ್ತು ಪ್ರಕೃತಿಯ ನಡುವೆ ಸಾಮೂಹಿಕ ಕ್ಷೇಮ ಕೂಟ.",
    price: 299,
    originalPrice: 599,
    duration: "2.5 Hours",
    timingSlot: "6:00 – 8:30 AM IST (Sunday Batch)",
    timingIcon: "hiking",
    badge: "Mysuru Shala Walk",
    image: "https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=800&q=80",
    features: [
      "Silent step mindfulness",
      "Panoramic sunrise vantage point",
      "Forest breathwork & grounding",
      "Herbal Mysuru decoction included"
    ],
    spotsLeft: 5,
    isActive: true
  },
  {
    slug: "weekend-retreat",
    section: "other",
    sectionLabel: "Other Activities",
    sectionLabelKn: "ಇತರ ಚಟುವಟಿಕೆಗಳು",
    title: "Weekend Shala Immersion & Satsang",
    titleKn: "ವಾರಾಂತ್ಯದ ಶಾಲಾ ತರಬೇತಿ & ಸತ್ಸಂಗ",
    category: "retreat",
    categoryLabel: "Shala Intensive",
    description: "2-day weekend immersive shala clinic. Includes posture alignment, Patanjali yoga sutra discussions, and direct interactive tea satsang with Sushii.",
    descriptionKn: "ವಾರಾಂತ್ಯದ ಎರಡು ದಿನಗಳ ವಿಶೇಷ ತರಬೇತಿ. ಆಸನಗಳ ಸೂಕ್ಷ್ಮ ಸರಿಪಡಿಸುವಿಕೆ, ಯೋಗ ಸೂತ್ರಗಳ ಅರ್ಥೈಸುವಿಕೆ ಮತ್ತು ಸುಶಿ ಅವರೊಂದಿಗೆ ಆಪ್ತ ಚರ್ಚೆ.",
    price: 699,
    originalPrice: 1299,
    duration: "2-Day Weekend",
    timingSlot: "7:00 – 11:30 AM IST (Sat & Sun)",
    timingIcon: "diversity_1",
    badge: "Deep Immersion",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
    features: [
      "Hands-on alignment correction",
      "Yoga philosophy & life habits",
      "Extended sound immersion",
      "Personalized practice routine audit"
    ],
    spotsLeft: 4,
    isActive: true
  },

  // ==================== COMBO PASS ====================
  {
    slug: "combo-pass",
    section: "yoga",
    sectionLabel: "All Access",
    sectionLabelKn: "ಎಲ್ಲಾ ಪ್ರವೇಶ",
    title: "All-Access Combo Pass",
    titleKn: "ಸಂಪೂರ್ಣ ಆರೋಗ್ಯ ಕಾಂಬೋ ಪಾಸ್",
    category: "combo",
    categoryLabel: "All Access",
    description: "Ultimate daily wellness system. Get Zoom links to all our classes. Join active Ashtanga/Strength in the morning and wind down with Sushii Nights before sleeping. Save ₹300/month.",
    descriptionKn: "ಸಂಪೂರ್ಣ ದೈನಂದಿನ ಆರೋಗ್ಯ ವ್ಯವಸ್ಥೆ. ನಮ್ಮ ಎಲ್ಲಾ ಲೈವ್ ತರಗತಿಗಳ ಜೂಮ್ ಲಿಂಕ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ. ಮುಂಜಾನೆ ಅಷ್ಟಾಂಗ/ಶಕ್ತಿ ತರಬೇತಿ ಮತ್ತು ಮಲಗುವ ಮುನ್ನ ಸುಶಿ ನೈಟ್ಸ್ ಅಭ್ಯಾಸ ಮಾಡಿ.",
    price: 599,
    originalPrice: 899,
    duration: "All Daily Batches",
    timingSlot: "All Daily Batches Access",
    timingIcon: "all_inclusive",
    badge: "Best Value",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAeW6X-Xbnzzibn5vBblDaMOKZ9I5pN1IM06R4zDRuOdkD-9Wo6S3m7m_J0dK0qdWJGyueyVkmQmwzk5BxGQIVpWVDXZhXVm80sJovk1mFz71N5ZhVHUenH4R4_9Bk3eTDTvbBT952IM8xLqwXcNFPzE8Fzq9jksT6GmEJpllQ1Vja4PrcRzI8jJaqJDwQsP41wdO6-Hd03gbX80NkyitBR2PCUNesuc1Hu0ObZ1sat3JWb4IooqiCC",
    features: [
      "All Daily Batches Across Yoga, Music & Activities",
      "24-Hour Zoom Class Recordings",
      "Private Community & WhatsApp Cohort Access",
      "Direct Monthly Q&A with Sushii"
    ],
    spotsLeft: 20,
    isActive: true
  }
];

const adminUser = {
  name: "Sushii - Founder & Lead Instructor",
  email: "admin@shashstudios.com",
  password: "ShashMysuru@2026",
  role: "superadmin",
  isActive: true
};

module.exports = { workshops, adminUser };
